version: '3.9'
services:
  database:
    image: mysql
    container_name: connect
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'connect'
      MYSQL_DATABASE: 'connect'
    ports:
      - '3307:3306'
 